#include "pch.h"
#include "SceneResources/TungstenLoading.h"

#include <algorithm>
#include <cfloat>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <unordered_map>
#include <vector>

#include <spdlog/spdlog.h>
#include <rapidjson/document.h>
#include <tinygltf/tiny_gltf.h>   // tinygltf::Image (reuses the glTF texture upload)
#include <tinygltf/stb_image.h>   // stbi_load prototypes; implementation in tiny_gltf.cc

#include "InputElements.h"
#include "ResourceManager/ResourceManagerTypes.h" // AssetId
#include "SceneResources/MeshProcessing.h"
#include "SceneResources/Scene.h"
#include "SceneResources/SceneNode.h"
#include "SceneResources/Model.h"
#include "SceneResources/Primitive.h"
#include "SceneResources/GameObject.h"
#include "SceneResources/Material.h"
#include "SceneResources/LightData.h"
#include "Resources/Buffer.h"
#include "Resources/VertexBuffer.h"
#include "Resources/IndexBuffer.h"
#include "Renderer.h"

namespace
{
    // Tungsten native mesh (.wo3): headerless — uint64 vertexCount, vertices,
    // uint64 triangleCount, triangles. Vertex = pos(3f)+normal(3f)+uv(2f) = 32 B;
    // triangle = 3 int32 indices + int32 material id = 16 B.
    #pragma pack(push, 1)
    struct Wo3Vertex { float px, py, pz, nx, ny, nz, u, v; };
    struct Wo3Triangle { int32_t i0, i1, i2, material; };
    #pragma pack(pop)
    static_assert(sizeof(Wo3Vertex) == 32, "Wo3Vertex must be 32 bytes");
    static_assert(sizeof(Wo3Triangle) == 16, "Wo3Triangle must be 16 bytes");

    bool LoadWo3(const std::filesystem::path& path, std::vector<Vertex>& outVertices, std::vector<uint32_t>& outIndices)
    {
        std::ifstream file(path, std::ios::binary);
        if (!file)
        {
            spdlog::error("Tungsten: cannot open mesh '{}'", path.string());
            return false;
        }

        uint64_t vertexCount = 0;
        file.read(reinterpret_cast<char*>(&vertexCount), sizeof(vertexCount));
        std::vector<Wo3Vertex> sourceVertices(static_cast<size_t>(vertexCount));
        if (vertexCount > 0)
            file.read(reinterpret_cast<char*>(sourceVertices.data()), static_cast<std::streamsize>(vertexCount * sizeof(Wo3Vertex)));

        uint64_t triangleCount = 0;
        file.read(reinterpret_cast<char*>(&triangleCount), sizeof(triangleCount));
        std::vector<Wo3Triangle> sourceTriangles(static_cast<size_t>(triangleCount));
        if (triangleCount > 0)
            file.read(reinterpret_cast<char*>(sourceTriangles.data()), static_cast<std::streamsize>(triangleCount * sizeof(Wo3Triangle)));

        if (!file)
        {
            spdlog::error("Tungsten: truncated mesh '{}'", path.string());
            return false;
        }

        outVertices.resize(static_cast<size_t>(vertexCount));
        for (size_t i = 0; i < outVertices.size(); ++i)
        {
            const Wo3Vertex& s = sourceVertices[i];
            Vertex& d = outVertices[i];
            d.Pos = { s.px, s.py, s.pz };
            d.Normal = { s.nx, s.ny, s.nz };
            d.Tangent = { 0.0f, 0.0f, 0.0f, 1.0f }; // generated by ComputeTangents
            d.Tex0 = { s.u, s.v };
        }

        // Canonical CCW winding: mirror the glTF loader — positions and winding
        // kept as authored (both formats are right-handed Y-up).
        outIndices.reserve(static_cast<size_t>(triangleCount) * 3);
        for (const Wo3Triangle& t : sourceTriangles)
        {
            outIndices.push_back(static_cast<uint32_t>(t.i0));
            outIndices.push_back(static_cast<uint32_t>(t.i1));
            outIndices.push_back(static_cast<uint32_t>(t.i2));
        }
        return true;
    }

    DirectX::SimpleMath::Vector3 ParseVec3(const rapidjson::Value& value, const DirectX::SimpleMath::Vector3& fallback)
    {
        if (value.IsArray() && value.Size() == 3)
            return { value[0].GetFloat(), value[1].GetFloat(), value[2].GetFloat() };
        return fallback;
    }

    // Tungsten scale: a scalar (uniform) or a 3-array.
    DirectX::SimpleMath::Vector3 ParseScale(const rapidjson::Value& value)
    {
        if (value.IsNumber())
        {
            const float s = value.GetFloat();
            return { s, s, s };
        }
        return ParseVec3(value, { 1.0f, 1.0f, 1.0f });
    }

    struct Rgb { float r, g, b; };

    // Approximate normal-incidence reflectance for Tungsten conductor presets
    // (ADR 0006: the metallic base colour). Values are eyeballed sRGB tints.
    Rgb ConductorPreset(const std::string& material)
    {
        if (material == "Al") return { 0.91f, 0.92f, 0.92f };
        if (material == "Cu") return { 0.95f, 0.64f, 0.54f };
        if (material == "Au") return { 1.00f, 0.78f, 0.34f };
        if (material == "Ag") return { 0.98f, 0.97f, 0.95f };
        if (material == "Fe") return { 0.56f, 0.57f, 0.58f };
        if (material == "Cr") return { 0.55f, 0.56f, 0.55f };
        if (material == "Ni") return { 0.66f, 0.61f, 0.53f };
        return { 0.90f, 0.90f, 0.90f }; // generic metal
    }

    // A Tungsten colour value: number (gray), 3-array (rgb), else fallback.
    Rgb ParseColor(const rapidjson::Value& value, const Rgb& fallback)
    {
        if (value.IsNumber())
        {
            const float v = value.GetFloat();
            return { v, v, v };
        }
        if (value.IsArray() && value.Size() >= 3)
            return { value[0].GetFloat(), value[1].GetFloat(), value[2].GetFloat() };
        return fallback;
    }

    struct AlbedoResult
    {
        Rgb color{ 0.8f, 0.8f, 0.8f };
        std::string texturePath; // relative to scene dir; empty = none
    };

    // Tungsten albedo: number | 3-array | texture-path string | procedural object
    // (checker → average of on/off, ADR 0006).
    AlbedoResult ParseAlbedo(const rapidjson::Value& bsdf)
    {
        AlbedoResult result;
        if (!bsdf.HasMember("albedo"))
            return result;

        const rapidjson::Value& albedo = bsdf["albedo"];
        if (albedo.IsString())
        {
            result.texturePath = albedo.GetString();
            result.color = { 1.0f, 1.0f, 1.0f }; // texture supplies colour
        }
        else if (albedo.IsObject())
        {
            const Rgb on = albedo.HasMember("on_color") ? ParseColor(albedo["on_color"], { 0.8f, 0.8f, 0.8f }) : Rgb{ 0.8f, 0.8f, 0.8f };
            const Rgb off = albedo.HasMember("off_color") ? ParseColor(albedo["off_color"], { 0.2f, 0.2f, 0.2f }) : Rgb{ 0.2f, 0.2f, 0.2f };
            result.color = { (on.r + off.r) * 0.5f, (on.g + off.g) * 0.5f, (on.b + off.b) * 0.5f };
            spdlog::warn("Tungsten: procedural albedo -> average constant colour");
        }
        else
        {
            result.color = ParseColor(albedo, result.color);
        }
        return result;
    }

    float ParseRoughness(const rapidjson::Value& bsdf, float fallback)
    {
        if (bsdf.HasMember("roughness") && bsdf["roughness"].IsNumber())
            return bsdf["roughness"].GetFloat();
        return fallback; // roughness textures not supported in v1
    }

    std::shared_ptr<Texture> LoadTextureFromFile(
        Renderer& renderer,
        const std::filesystem::path& path,
        std::unordered_map<std::string, std::shared_ptr<Texture>>& cache)
    {
        const std::string key = path.string();
        auto it = cache.find(key);
        if (it != cache.end())
            return it->second;

        int width = 0, height = 0, channels = 0;
        stbi_uc* pixels = stbi_load(key.c_str(), &width, &height, &channels, 4);
        if (!pixels)
        {
            spdlog::warn("Tungsten: failed to load texture '{}'", key);
            cache[key] = nullptr;
            return nullptr;
        }

        tinygltf::Image image;
        image.width = width;
        image.height = height;
        image.component = 4;
        image.bits = 8;
        image.pixel_type = TINYGLTF_COMPONENT_TYPE_UNSIGNED_BYTE;
        image.image.assign(pixels, pixels + static_cast<size_t>(width) * height * 4);
        stbi_image_free(pixels);

        std::shared_ptr<Texture> texture = renderer.CreateTextureFromGLTF(image);
        cache[key] = texture;
        return texture;
    }

    // Map a Tungsten BSDF onto the engine's Cook-Torrance metallic-roughness
    // material (ADR 0006). Glass is opaque-approximated; the coat is dropped.
    std::shared_ptr<Material> MakeMaterialFromBsdf(
        Renderer& renderer,
        const rapidjson::Value& bsdf,
        const std::filesystem::path& sceneDir,
        std::unordered_map<std::string, std::shared_ptr<Texture>>& textureCache)
    {
        auto material = std::make_shared<Material>();

        const std::string type = bsdf.HasMember("type") && bsdf["type"].IsString() ? bsdf["type"].GetString() : "";
        const AlbedoResult albedo = ParseAlbedo(bsdf);

        float metallic = 0.0f;
        float roughness = 1.0f;
        Rgb color = albedo.color;

        if (type == "lambert" || type == "oren_nayar")
        {
            metallic = 0.0f; roughness = 1.0f;
        }
        else if (type == "rough_conductor" || type == "conductor")
        {
            metallic = 1.0f;
            roughness = ParseRoughness(bsdf, 0.1f);
            if (bsdf.HasMember("material") && bsdf["material"].IsString())
                color = ConductorPreset(bsdf["material"].GetString());
        }
        else if (type == "mirror")
        {
            metallic = 1.0f; roughness = 0.0f;
            if (!bsdf.HasMember("albedo")) color = { 1.0f, 1.0f, 1.0f };
        }
        else if (type == "rough_plastic" || type == "plastic" || type == "smooth_coat" || type == "phong")
        {
            metallic = 0.0f;
            roughness = ParseRoughness(bsdf, 0.5f);
        }
        else if (type == "dielectric" || type == "rough_dielectric" || type == "thinsheet")
        {
            // No transmission in the engine: opaque, slightly glossy, tinted (LOSSY).
            metallic = 0.0f;
            roughness = ParseRoughness(bsdf, 0.1f);
            if (!bsdf.HasMember("albedo")) color = { 0.9f, 0.9f, 0.9f };
        }
        else if (type == "null")
        {
            metallic = 0.0f; roughness = 1.0f; color = { 0.5f, 0.5f, 0.5f };
        }
        else
        {
            spdlog::warn("Tungsten: unmapped BSDF type '{}' -> diffuse gray", type);
            metallic = 0.0f; roughness = 1.0f; color = { 0.8f, 0.8f, 0.8f };
        }

        material->m_data.baseColorFactor = { color.r, color.g, color.b, 1.0f };
        material->m_data.metallicFactor = metallic;
        material->m_data.roughnessFactor = roughness;

        if (!albedo.texturePath.empty())
            material->m_albedoTexture = LoadTextureFromFile(renderer, sceneDir / albedo.texturePath, textureCache);

        material->UpdateMaterial();
        return material;
    }
}

std::shared_ptr<Scene> TungstenLoading::LoadScene(Renderer& renderer, const AssetId& assetId)
{
    using namespace DirectX;
    namespace fs = std::filesystem;

    const fs::path scenePath = assetId.AsPath();
    const fs::path sceneDir = scenePath.parent_path();

    std::ifstream in(scenePath, std::ios::binary);
    if (!in)
    {
        spdlog::error("Tungsten: cannot open scene '{}'", scenePath.string());
        return nullptr;
    }
    std::string json((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    if (json.size() >= 3 && static_cast<unsigned char>(json[0]) == 0xEF &&
        static_cast<unsigned char>(json[1]) == 0xBB && static_cast<unsigned char>(json[2]) == 0xBF)
        json.erase(0, 3); // strip UTF-8 BOM (rapidjson chokes on it)

    rapidjson::Document doc;
    doc.Parse(json.c_str());
    if (doc.HasParseError() || !doc.IsObject())
    {
        spdlog::error("Tungsten: JSON parse error in '{}'", scenePath.string());
        return nullptr;
    }

    SceneBuilder sceneBuilder;
    sceneBuilder.SetName(assetId.AsString());

    std::vector<Vertex> vertices;
    std::vector<uint32_t> indices;

    // BSDF library: primitives reference these by name (or inline an object).
    std::unordered_map<std::string, const rapidjson::Value*> bsdfsByName;
    if (doc.HasMember("bsdfs") && doc["bsdfs"].IsArray())
        for (const rapidjson::Value& bsdf : doc["bsdfs"].GetArray())
            if (bsdf.HasMember("name") && bsdf["name"].IsString())
                bsdfsByName[bsdf["name"].GetString()] = &bsdf;

    std::unordered_map<std::string, std::shared_ptr<Texture>> textureCache;

    int meshCount = 0, skippedCount = 0;

    if (doc.HasMember("primitives") && doc["primitives"].IsArray())
    {
        for (const rapidjson::Value& prim : doc["primitives"].GetArray())
        {
            const char* type = prim.HasMember("type") && prim["type"].IsString() ? prim["type"].GetString() : "";

            if (std::string(type) != "mesh" || !prim.HasMember("file") || !prim["file"].IsString())
            {
                // Analytic quad/cube/sphere and emitter-only primitives: not v1.
                ++skippedCount;
                continue;
            }

            const fs::path meshPath = sceneDir / prim["file"].GetString();
            std::vector<Vertex> primVertices;
            std::vector<uint32_t> primIndices;
            if (!LoadWo3(meshPath, primVertices, primIndices) || primVertices.empty() || primIndices.empty())
            {
                ++skippedCount;
                continue;
            }

            MeshUtils::DropDegenerateTriangles(primVertices, primIndices);
            MeshUtils::ComputeTangents(primVertices, primIndices); // .wo3 carries normals, not tangents
            MeshUtils::EnforceVertexInvariants(primVertices);

            BufferView vertexView{};
            vertexView.buffer = nullptr;
            vertexView.count = primVertices.size();
            vertexView.offset = vertices.size();
            vertexView.offsetBytes = vertices.size() * sizeof(Vertex);
            vertexView.size = primVertices.size() * sizeof(Vertex);

            BufferView indexView{};
            indexView.buffer = nullptr;
            indexView.count = primIndices.size();
            indexView.offset = indices.size();
            indexView.offsetBytes = indices.size() * sizeof(uint32_t);
            indexView.size = primIndices.size() * sizeof(uint32_t);

            XMFLOAT3 localMin{ FLT_MAX, FLT_MAX, FLT_MAX };
            XMFLOAT3 localMax{ -FLT_MAX, -FLT_MAX, -FLT_MAX };
            for (const Vertex& v : primVertices)
            {
                localMin.x = std::min(localMin.x, v.Pos.x); localMax.x = std::max(localMax.x, v.Pos.x);
                localMin.y = std::min(localMin.y, v.Pos.y); localMax.y = std::max(localMax.y, v.Pos.y);
                localMin.z = std::min(localMin.z, v.Pos.z); localMax.z = std::max(localMax.z, v.Pos.z);
            }

            // Resolve the primitive's BSDF (named reference or inline object).
            std::shared_ptr<Material> material;
            if (prim.HasMember("bsdf"))
            {
                const rapidjson::Value& bsdfRef = prim["bsdf"];
                if (bsdfRef.IsString())
                {
                    auto it = bsdfsByName.find(bsdfRef.GetString());
                    if (it != bsdfsByName.end())
                        material = MakeMaterialFromBsdf(renderer, *it->second, sceneDir, textureCache);
                    else
                        spdlog::warn("Tungsten: primitive references unknown bsdf '{}'", bsdfRef.GetString());
                }
                else if (bsdfRef.IsObject())
                {
                    material = MakeMaterialFromBsdf(renderer, bsdfRef, sceneDir, textureCache);
                }
            }
            if (!material)
            {
                material = std::make_shared<Material>();
                material->m_data.baseColorFactor = { 0.8f, 0.8f, 0.8f, 1.0f };
                material->m_data.metallicFactor = 0.0f;
                material->m_data.roughnessFactor = 1.0f;
                material->UpdateMaterial();
            }

            vertices.insert(vertices.end(), primVertices.begin(), primVertices.end());
            indices.insert(indices.end(), primIndices.begin(), primIndices.end());

            auto primitive = std::make_shared<Primitive>(vertexView, indexView, material);
            primitive->m_localAabbMin = localMin;
            primitive->m_localAabbMax = localMax;

            auto model = std::make_shared<Model>();
            model->AddMesh(primitive);
            sceneBuilder.AddModel(model);

            auto gameObject = renderer.InstantiateGameObject();
            sceneBuilder.AddGameObject(gameObject, model);

            auto node = std::make_shared<SceneNode>();
            node->AddGameObject(gameObject);

            SimpleMath::Vector3 position{ 0, 0, 0 };
            SimpleMath::Vector3 scale{ 1, 1, 1 };
            SimpleMath::Vector3 rotationDeg{ 0, 0, 0 };
            if (prim.HasMember("transform") && prim["transform"].IsObject())
            {
                const rapidjson::Value& transform = prim["transform"];
                if (transform.HasMember("position")) position = ParseVec3(transform["position"], position);
                if (transform.HasMember("scale")) scale = ParseScale(transform["scale"]);
                if (transform.HasMember("rotation")) rotationDeg = ParseVec3(transform["rotation"], rotationDeg);
            }

            const float toRad = 3.14159265358979323846f / 180.0f;
            // Tungsten rotation = XYZ Euler degrees. Single-axis cases (this scene)
            // are order/handedness-robust; verify sign on multi-axis scenes.
            SimpleMath::Quaternion rotation = SimpleMath::Quaternion::CreateFromYawPitchRoll(
                rotationDeg.y * toRad, rotationDeg.x * toRad, rotationDeg.z * toRad);

            node->SetScale(scale);
            node->SetRotation(rotation);
            node->SetPosition(position);
            sceneBuilder.AddChild(sceneBuilder.GetRoot(), node);

            ++meshCount;
        }
    }

    spdlog::info("Tungsten: loaded {} mesh primitive(s), skipped {} (analytic/emitter/failed)", meshCount, skippedCount);

    if (meshCount == 0)
    {
        spdlog::error("Tungsten: no mesh geometry loaded from '{}'", scenePath.string());
        return nullptr;
    }

    // v1: no Tungsten emitters/env imported — engine default directional light.
    LightData defaultLight;
    defaultLight.type = Directional;
    defaultLight.position = { 0, 0, 0 };
    defaultLight.direction = { -0.5f, -0.7071f, -0.067f };
    defaultLight.color = { 1, 1, 1 };
    defaultLight.intensity = 3.0f;
    defaultLight.range = 0.0f;
    sceneBuilder.AddLightData(defaultLight);

    auto vertexIndexPair = renderer.CreateSceneResources(vertices, indices);
    auto vertexBuffer = vertexIndexPair.first;
    auto indexBuffer = vertexIndexPair.second;
    sceneBuilder.SetVertexBuffer(vertexBuffer);
    sceneBuilder.SetIndexBuffer(indexBuffer);

    for (auto model : sceneBuilder.GetModels())
    {
        for (auto primitive : model->GetMeshes())
        {
            primitive->m_vertexBufferOffset.buffer = std::static_pointer_cast<Buffer>(vertexBuffer);
            primitive->m_indexBufferOffset.buffer = std::static_pointer_cast<Buffer>(indexBuffer);
        }
    }

    sceneBuilder.UpdateMatrices();
    sceneBuilder.SetAccelerationStructures(MeshUtils::BuildAccelerationStructures(renderer, sceneBuilder));

    return sceneBuilder.Build(renderer);
}
