#include "pch.h"
#include "SceneResources/TungstenLoading.h"

#include <algorithm>
#include <cfloat>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include <spdlog/spdlog.h>
#include <rapidjson/document.h>

#include "InputElements.h"
#include "ResourceManager/ResourceManagerTypes.h" // AssetId
#include "SceneResources/MeshProcessing.h"
#include "SceneResources/Scene.h"
#include "SceneResources/SceneNode.h"
#include "SceneResources/Model.h"
#include "SceneResources/Primitive.h"
#include "SceneResources/GameObject.h"
#include "SceneResources/Material.h"
#include "SceneResources/LightData.h"
#include "Resources/Buffer.h"
#include "Resources/VertexBuffer.h"
#include "Resources/IndexBuffer.h"
#include "Renderer.h"

namespace
{
    // Tungsten native mesh (.wo3): headerless — uint64 vertexCount, vertices,
    // uint64 triangleCount, triangles. Vertex = pos(3f)+normal(3f)+uv(2f) = 32 B;
    // triangle = 3 int32 indices + int32 material id = 16 B.
    #pragma pack(push, 1)
    struct Wo3Vertex { float px, py, pz, nx, ny, nz, u, v; };
    struct Wo3Triangle { int32_t i0, i1, i2, material; };
    #pragma pack(pop)
    static_assert(sizeof(Wo3Vertex) == 32, "Wo3Vertex must be 32 bytes");
    static_assert(sizeof(Wo3Triangle) == 16, "Wo3Triangle must be 16 bytes");

    bool LoadWo3(const std::filesystem::path& path, std::vector<Vertex>& outVertices, std::vector<uint32_t>& outIndices)
    {
        std::ifstream file(path, std::ios::binary);
        if (!file)
        {
            spdlog::error("Tungsten: cannot open mesh '{}'", path.string());
            return false;
        }

        uint64_t vertexCount = 0;
        file.read(reinterpret_cast<char*>(&vertexCount), sizeof(vertexCount));
        std::vector<Wo3Vertex> sourceVertices(static_cast<size_t>(vertexCount));
        if (vertexCount > 0)
            file.read(reinterpret_cast<char*>(sourceVertices.data()), static_cast<std::streamsize>(vertexCount * sizeof(Wo3Vertex)));

        uint64_t triangleCount = 0;
        file.read(reinterpret_cast<char*>(&triangleCount), sizeof(triangleCount));
        std::vector<Wo3Triangle> sourceTriangles(static_cast<size_t>(triangleCount));
        if (triangleCount > 0)
            file.read(reinterpret_cast<char*>(sourceTriangles.data()), static_cast<std::streamsize>(triangleCount * sizeof(Wo3Triangle)));

        if (!file)
        {
            spdlog::error("Tungsten: truncated mesh '{}'", path.string());
            return false;
        }

        outVertices.resize(static_cast<size_t>(vertexCount));
        for (size_t i = 0; i < outVertices.size(); ++i)
        {
            const Wo3Vertex& s = sourceVertices[i];
            Vertex& d = outVertices[i];
            d.Pos = { s.px, s.py, s.pz };
            d.Normal = { s.nx, s.ny, s.nz };
            d.Tangent = { 0.0f, 0.0f, 0.0f, 1.0f }; // generated by ComputeTangents
            d.Tex0 = { s.u, s.v };
        }

        // Canonical CCW winding: mirror the glTF loader — positions and winding
        // kept as authored (both formats are right-handed Y-up).
        outIndices.reserve(static_cast<size_t>(triangleCount) * 3);
        for (const Wo3Triangle& t : sourceTriangles)
        {
            outIndices.push_back(static_cast<uint32_t>(t.i0));
            outIndices.push_back(static_cast<uint32_t>(t.i1));
            outIndices.push_back(static_cast<uint32_t>(t.i2));
        }
        return true;
    }

    DirectX::SimpleMath::Vector3 ParseVec3(const rapidjson::Value& value, const DirectX::SimpleMath::Vector3& fallback)
    {
        if (value.IsArray() && value.Size() == 3)
            return { value[0].GetFloat(), value[1].GetFloat(), value[2].GetFloat() };
        return fallback;
    }

    // Tungsten scale: a scalar (uniform) or a 3-array.
    DirectX::SimpleMath::Vector3 ParseScale(const rapidjson::Value& value)
    {
        if (value.IsNumber())
        {
            const float s = value.GetFloat();
            return { s, s, s };
        }
        return ParseVec3(value, { 1.0f, 1.0f, 1.0f });
    }
}

std::shared_ptr<Scene> TungstenLoading::LoadScene(Renderer& renderer, const AssetId& assetId)
{
    using namespace DirectX;
    namespace fs = std::filesystem;

    const fs::path scenePath = assetId.AsPath();
    const fs::path sceneDir = scenePath.parent_path();

    std::ifstream in(scenePath, std::ios::binary);
    if (!in)
    {
        spdlog::error("Tungsten: cannot open scene '{}'", scenePath.string());
        return nullptr;
    }
    std::string json((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    if (json.size() >= 3 && static_cast<unsigned char>(json[0]) == 0xEF &&
        static_cast<unsigned char>(json[1]) == 0xBB && static_cast<unsigned char>(json[2]) == 0xBF)
        json.erase(0, 3); // strip UTF-8 BOM (rapidjson chokes on it)

    rapidjson::Document doc;
    doc.Parse(json.c_str());
    if (doc.HasParseError() || !doc.IsObject())
    {
        spdlog::error("Tungsten: JSON parse error in '{}'", scenePath.string());
        return nullptr;
    }

    SceneBuilder sceneBuilder;
    sceneBuilder.SetName(assetId.AsString());

    std::vector<Vertex> vertices;
    std::vector<uint32_t> indices;

    int meshCount = 0, skippedCount = 0;

    if (doc.HasMember("primitives") && doc["primitives"].IsArray())
    {
        for (const rapidjson::Value& prim : doc["primitives"].GetArray())
        {
            const char* type = prim.HasMember("type") && prim["type"].IsString() ? prim["type"].GetString() : "";

            if (std::string(type) != "mesh" || !prim.HasMember("file") || !prim["file"].IsString())
            {
                // Analytic quad/cube/sphere and emitter-only primitives: not v1.
                ++skippedCount;
                continue;
            }

            const fs::path meshPath = sceneDir / prim["file"].GetString();
            std::vector<Vertex> primVertices;
            std::vector<uint32_t> primIndices;
            if (!LoadWo3(meshPath, primVertices, primIndices) || primVertices.empty() || primIndices.empty())
            {
                ++skippedCount;
                continue;
            }

            MeshUtils::DropDegenerateTriangles(primVertices, primIndices);
            MeshUtils::ComputeTangents(primVertices, primIndices); // .wo3 carries normals, not tangents
            MeshUtils::EnforceVertexInvariants(primVertices);

            BufferView vertexView{};
            vertexView.buffer = nullptr;
            vertexView.count = primVertices.size();
            vertexView.offset = vertices.size();
            vertexView.offsetBytes = vertices.size() * sizeof(Vertex);
            vertexView.size = primVertices.size() * sizeof(Vertex);

            BufferView indexView{};
            indexView.buffer = nullptr;
            indexView.count = primIndices.size();
            indexView.offset = indices.size();
            indexView.offsetBytes = indices.size() * sizeof(uint32_t);
            indexView.size = primIndices.size() * sizeof(uint32_t);

            XMFLOAT3 localMin{ FLT_MAX, FLT_MAX, FLT_MAX };
            XMFLOAT3 localMax{ -FLT_MAX, -FLT_MAX, -FLT_MAX };
            for (const Vertex& v : primVertices)
            {
                localMin.x = std::min(localMin.x, v.Pos.x); localMax.x = std::max(localMax.x, v.Pos.x);
                localMin.y = std::min(localMin.y, v.Pos.y); localMax.y = std::max(localMax.y, v.Pos.y);
                localMin.z = std::min(localMin.z, v.Pos.z); localMax.z = std::max(localMax.z, v.Pos.z);
            }

            // v1 material: neutral diffuse. BSDF mapping + textures land in Stage 4.
            auto material = std::make_shared<Material>();
            material->m_data.baseColorFactor = { 0.8f, 0.8f, 0.8f, 1.0f };
            material->m_data.metallicFactor = 0.0f;
            material->m_data.roughnessFactor = 1.0f;
            material->UpdateMaterial();

            vertices.insert(vertices.end(), primVertices.begin(), primVertices.end());
            indices.insert(indices.end(), primIndices.begin(), primIndices.end());

            auto primitive = std::make_shared<Primitive>(vertexView, indexView, material);
            primitive->m_localAabbMin = localMin;
            primitive->m_localAabbMax = localMax;

            auto model = std::make_shared<Model>();
            model->AddMesh(primitive);
            sceneBuilder.AddModel(model);

            auto gameObject = renderer.InstantiateGameObject();
            sceneBuilder.AddGameObject(gameObject, model);

            auto node = std::make_shared<SceneNode>();
            node->AddGameObject(gameObject);

            SimpleMath::Vector3 position{ 0, 0, 0 };
            SimpleMath::Vector3 scale{ 1, 1, 1 };
            SimpleMath::Vector3 rotationDeg{ 0, 0, 0 };
            if (prim.HasMember("transform") && prim["transform"].IsObject())
            {
                const rapidjson::Value& transform = prim["transform"];
                if (transform.HasMember("position")) position = ParseVec3(transform["position"], position);
                if (transform.HasMember("scale")) scale = ParseScale(transform["scale"]);
                if (transform.HasMember("rotation")) rotationDeg = ParseVec3(transform["rotation"], rotationDeg);
            }

            const float toRad = 3.14159265358979323846f / 180.0f;
            // Tungsten rotation = XYZ Euler degrees. Single-axis cases (this scene)
            // are order/handedness-robust; verify sign on multi-axis scenes.
            SimpleMath::Quaternion rotation = SimpleMath::Quaternion::CreateFromYawPitchRoll(
                rotationDeg.y * toRad, rotationDeg.x * toRad, rotationDeg.z * toRad);

            node->SetScale(scale);
            node->SetRotation(rotation);
            node->SetPosition(position);
            sceneBuilder.AddChild(sceneBuilder.GetRoot(), node);

            ++meshCount;
        }
    }

    spdlog::info("Tungsten: loaded {} mesh primitive(s), skipped {} (analytic/emitter/failed)", meshCount, skippedCount);

    if (meshCount == 0)
    {
        spdlog::error("Tungsten: no mesh geometry loaded from '{}'", scenePath.string());
        return nullptr;
    }

    // v1: no Tungsten emitters/env imported — engine default directional light.
    LightData defaultLight;
    defaultLight.type = Directional;
    defaultLight.position = { 0, 0, 0 };
    defaultLight.direction = { -0.5f, -0.7071f, -0.067f };
    defaultLight.color = { 1, 1, 1 };
    defaultLight.intensity = 3.0f;
    defaultLight.range = 0.0f;
    sceneBuilder.AddLightData(defaultLight);

    auto vertexIndexPair = renderer.CreateSceneResources(vertices, indices);
    auto vertexBuffer = vertexIndexPair.first;
    auto indexBuffer = vertexIndexPair.second;
    sceneBuilder.SetVertexBuffer(vertexBuffer);
    sceneBuilder.SetIndexBuffer(indexBuffer);

    for (auto model : sceneBuilder.GetModels())
    {
        for (auto primitive : model->GetMeshes())
        {
            primitive->m_vertexBufferOffset.buffer = std::static_pointer_cast<Buffer>(vertexBuffer);
            primitive->m_indexBufferOffset.buffer = std::static_pointer_cast<Buffer>(indexBuffer);
        }
    }

    sceneBuilder.UpdateMatrices();
    sceneBuilder.SetAccelerationStructures(MeshUtils::BuildAccelerationStructures(renderer, sceneBuilder));

    return sceneBuilder.Build(renderer);
}
